spring.application.name=artigos

# Porta da API
server.port=8080

# endpoint padrão
server.servlet.context-path=/api/v1

# Configurações de rotas invalidas
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false